"use client";

export interface FacilityOption {
  id: string;
  name: string;
}

export const LT_FACILITIES: FacilityOption[] = [
  { id: "LT_F1", name: "Valley View" },
  { id: "LT_F3", name: "COR-1" },
  { id: "LT_F4", name: "Morgan Lakes" },
  { id: "LT_F5", name: "Spring-902" },
  { id: "LT_F6", name: "Transcon-838" },
  { id: "LT_F7", name: "Delp-892" },
  { id: "LT_F8", name: "Sacramento" },
  { id: "LT_F9", name: "Charleston" },
  { id: "LT_F10", name: "Gardena" },
  { id: "LT_F10002", name: "Citypark" },
  { id: "LT_F11", name: "Alessandro" },
  { id: "LT_F12", name: "Gougar" },
  { id: "LT_F13", name: "Hazelton" },
  { id: "LT_F131", name: "146-El Paso" },
  { id: "LT_F132", name: "151-VGT" },
  { id: "LT_F133", name: "152-Somerset" },
  { id: "LT_F135", name: "Moreno Valley" },
  { id: "LT_F136", name: "158-Suffolk" },
  { id: "LT_F14", name: "Tacoma" },
  { id: "LT_F15", name: "Holt" },
  { id: "LT_F16", name: "Greenwood" },
  { id: "LT_F17", name: "Bolingbrook" },
  { id: "LT_F18", name: "Coppell" },
  { id: "LT_F19", name: "Seabrook" },
  { id: "LT_F20", name: "Tucker" },
  { id: "LT_F21", name: "Cesanek" },
  { id: "LT_F22", name: "Lincoln" },
  { id: "LT_F23", name: "Kent" },
  { id: "LT_F25", name: "Roanoke" },
  { id: "LT_F27", name: "Tolleson" },
  { id: "LT_F29", name: "Goodyear" },
  { id: "LT_F31", name: "Prosperity" },
  { id: "LT_F32", name: "Navigation" },
  { id: "LT_F33", name: "Douglasville" },
  { id: "LT_F34", name: "Cotton" },
  { id: "LT_F35", name: "Cyprus" },
  { id: "LT_F36", name: "St John" },
  { id: "LT_F37", name: "Ignition" },
  { id: "LT_F38", name: "Cassens" },
  { id: "LT_F39", name: "Wiegman" },
  { id: "LT_F40", name: "Vista" },
  { id: "LT_F41", name: "Gifford" },
  { id: "LT_F42", name: "Airport" },
  { id: "LT_F43", name: "Portsmouth" },
  { id: "LT_F44", name: "Suffolk" },
  { id: "LT_F45", name: "Doolittle" },
  { id: "LT_F46", name: "La Mirada" },
  { id: "LT_F47", name: "UNIS House" },
  { id: "LT_F59", name: "University Park" },
  { id: "LT_F98", name: "Plano" },
  { id: "LT_ORG-2", name: "Walnut" },
  { id: "LT_ORG-7455", name: "Ontario" },
  { id: "LT_ORG-7656", name: "Via Baron" },
  { id: "LT_ORG-7759", name: "Fontana" },
  { id: "LT_ORG-77709", name: "Quality 4400" },
  { id: "LT_ORG-7941", name: "Willow" },
  { id: "LT_ORG-7954", name: "Marlay" },
  { id: "LT_ORG-7955", name: "Turnbull" },
  { id: "LT_ORG-7972", name: "Hayward" },
  { id: "LT_ORG-7990", name: "Reyes" },
  { id: "LT_ORG-8125", name: "Valley" },
  { id: "LT_ORG-8126", name: "Texas" },
  { id: "LT_ORG-8127", name: "Indiana" },
  { id: "LT_ORG-34646", name: "New Jersey" },
  { id: "LT_ORG-34647", name: "Houston" },
  { id: "LT_ORG-35184", name: "Savannah" },
  { id: "LT_ORG-45230", name: "Red Bluff" },
  { id: "LT_ORG-50100", name: "Murphy" },
  { id: "LT_ORG-61213", name: "Joliet" },
  { id: "LT_ORG-67669", name: "Innovation" },
];

export function getFacilityName(facilityId: string): string {
  const found = LT_FACILITIES.find((f) => f.id === facilityId);
  return found?.name || facilityId.replace(/^LT_/, "").replace(/_/g, " ");
}
